/*
 * The MIT License
 *
 * Copyright 2023 joao.faria.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
package br.com.projetotdm.telas.SubsTelas;

import br.com.projetotdm.DAO.ModuloConexao;
import br.com.projetotdm.DAO.ModuloConexao;
import java.sql.Connection;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;
/**
 *
 * @author joao.faria
 */
public class SubTelaRelatorio3 extends javax.swing.JInternalFrame {

    /**
     * Creates new form SubTelaRelatorio3
     */
    Connection conexao = null;
    public SubTelaRelatorio3() {
        initComponents();
        conexao = ModuloConexao.conector();
    }
    public void gerar_relatorio_cte() {
    
    int confirma = JOptionPane.showConfirmDialog(null, "Confirma a geração deste relatório?", "Atenção", JOptionPane.YES_NO_OPTION);
        if (confirma == JOptionPane.YES_OPTION) {

            //IMPRIMINDO O RELATORIO COM O jasper
            try {

                String cte=txt_relatorio_cte.getText();
                String filial=txt_relatorio_filial.getText();
                String serie=txt_relatorio_serie.getText();
                

                    Map<String, Object> parametros = new HashMap<>();
                    parametros.put("cte", cte);
                    parametros.put("filial", filial);
                    parametros.put("serie", serie);

                    JasperPrint print = JasperFillManager.fillReport("C:\\Sistema de Avarias\\Relatorio\\RELATORIO-FILTRO-CTE-FILIAL-SERIE.jasper", parametros, conexao);
                    // Verifica se o relatório gerou páginas
                    if (print.getPages().isEmpty()) {
                        // Se não houver páginas, exibe uma mensagem personalizada
                        JOptionPane.showMessageDialog(null, "CTE não localizado!");
                    } else {
                        // Se houver páginas, exibe o JasperViewer
                        JasperViewer.viewReport(print, false);
                    }
                

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_relatorio_filial = new javax.swing.JLabel();
        txt_relatorio_filial = new javax.swing.JTextField();
        lbl_relatorio_serie = new javax.swing.JLabel();
        txt_relatorio_serie = new javax.swing.JTextField();
        txt_relatorio_cte = new javax.swing.JTextField();
        lbl_relatorio_cte = new javax.swing.JLabel();
        gerar_relatorio = new javax.swing.JButton();

        setClosable(true);
        setTitle("Relatorio por Filial/Serie/CTE");

        lbl_relatorio_filial.setText("Filial:");

        txt_relatorio_filial.setColumns(5);

        lbl_relatorio_serie.setText("Série:");

        txt_relatorio_serie.setColumns(5);

        txt_relatorio_cte.setColumns(5);

        lbl_relatorio_cte.setText("CTE:");

        gerar_relatorio.setText("Gerar");
        gerar_relatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gerar_relatorioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(gerar_relatorio)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_relatorio_filial)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_relatorio_filial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_relatorio_serie)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_relatorio_serie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_relatorio_cte)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_relatorio_cte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_relatorio_filial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_relatorio_filial)
                    .addComponent(lbl_relatorio_serie)
                    .addComponent(txt_relatorio_serie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_relatorio_cte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_relatorio_cte))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(gerar_relatorio)
                .addGap(21, 21, 21))
        );

        setBounds(340, 250, 368, 184);
    }// </editor-fold>//GEN-END:initComponents

    private void gerar_relatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gerar_relatorioActionPerformed
        if(txt_relatorio_cte.getText().isEmpty() && txt_relatorio_filial.getText().isEmpty() && txt_relatorio_serie.getText().isEmpty()){
            JOptionPane.showMessageDialog(rootPane,"Preencha todos os dados para gerar o relátorio.");
        }else{
            gerar_relatorio_cte();
        }
    }//GEN-LAST:event_gerar_relatorioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton gerar_relatorio;
    private javax.swing.JLabel lbl_relatorio_cte;
    private javax.swing.JLabel lbl_relatorio_filial;
    private javax.swing.JLabel lbl_relatorio_serie;
    private javax.swing.JTextField txt_relatorio_cte;
    private javax.swing.JTextField txt_relatorio_filial;
    private javax.swing.JTextField txt_relatorio_serie;
    // End of variables declaration//GEN-END:variables
}
