/*
 * The MIT License
 *
 * Copyright 2023 João Victor Souza de Faria.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
package br.com.projetotdm.telas.SubsTelas;

import br.com.projetotdm.telas.TelasCadastros.TelaAvarias;
import br.com.projetotdm.DAO.ModuloConexao;
import java.sql.*;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;


/**
 * Sub-Tela de Pesquisa de Produtos.
 *
 * @author João Victor Souza de Faria
 * @version 1.1
 *
 */
public class TelaPesquisarProd extends javax.swing.JFrame {

    Connection conexao = null;
    PreparedStatement pst = null;
    ResultSet rs = null;

    private TelaAvarias telaAvarias;
    
    /**
     * Inicialização dos componentes da tela
     * 
     */

    public TelaPesquisarProd() {
        conexao = ModuloConexao.conector();
        initComponents();
    }
    /**
     * Seta dados na tela de avarias.
     * @param telaAvarias 
     */

    public void setTelaAvarias(TelaAvarias telaAvarias) {
        this.telaAvarias = telaAvarias;

    }
    /**
     * Metodo para buscar dados.
     */

    private void buscar() {

        String instru_sql = "select produto_id as ID,produto_nome as Nome,produto_descri as Descrição,produto_valor as Valor,produto_marca as Marca from tbproduto where produto_nome like ?";

        try {
            pst = conexao.prepareCall(instru_sql);
            pst.setString(1, txt_pesquisarprod_buscar.getText() + "%");
            rs = pst.executeQuery();

            // biblioteca rs2xml.jar para preencher as tabelas
            tbl_pesquisarprod_produtos.setModel(DbUtils.resultSetToTableModel(rs));

        } catch (Exception e) {
            System.out.println("Ocorreu um erro:" + e);
        }

    }
    /**
     * Metodo para adicionar Produto no banco de dados.
     */

    public void adicionar_produto() {
        int selectedRow = tbl_pesquisarprod_produtos.getSelectedRow();

        if (selectedRow != -1) {
            if (txt_pesquisarprod_quant.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Preencha a quantidade!");
            } else {
                String id = tbl_pesquisarprod_produtos.getValueAt(selectedRow, 0).toString();
                String nome = tbl_pesquisarprod_produtos.getValueAt(selectedRow, 1).toString();
                String valor = tbl_pesquisarprod_produtos.getValueAt(selectedRow, 3).toString();
                String quantidade = txt_pesquisarprod_quant.getText();
                

                telaAvarias.setDadosTelaAvarias(id, nome, valor, quantidade);
                dispose();
            }
        } else {
            JOptionPane.showMessageDialog(this, "Selecione um produto antes de adicionar.", "Aviso", JOptionPane.WARNING_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_pesquisarprod_produtos = new javax.swing.JTable();
        btn_pesquisarprod_buscar = new javax.swing.JButton();
        txt_pesquisarprod_buscar = new javax.swing.JTextField();
        lbl_pesquisarprod_buscar = new javax.swing.JLabel();
        lbl_pesquisarprod_quant = new javax.swing.JLabel();
        txt_pesquisarprod_quant = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pesquisar produtos");
        setIconImage(new ImageIcon(getClass().getResource("/br/com/projetotdm/icones/logotdms.png")).getImage());

        jButton1.setText("Adicionar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        tbl_pesquisarprod_produtos = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex){
                return false;

            }
        };
        tbl_pesquisarprod_produtos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Nome", "Descrição ", "Valor", "Marca"
            }
        ));
        tbl_pesquisarprod_produtos.setFocusable(false);
        tbl_pesquisarprod_produtos.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tbl_pesquisarprod_produtos);

        btn_pesquisarprod_buscar.setText("Buscar");
        btn_pesquisarprod_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pesquisarprod_buscarActionPerformed(evt);
            }
        });

        txt_pesquisarprod_buscar.setColumns(25);
        txt_pesquisarprod_buscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_pesquisarprod_buscarKeyPressed(evt);
            }
        });

        lbl_pesquisarprod_buscar.setText("Busca de produtos:");

        lbl_pesquisarprod_quant.setText("Quantidade:");

        txt_pesquisarprod_quant.setColumns(15);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 466, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lbl_pesquisarprod_buscar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_pesquisarprod_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_pesquisarprod_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lbl_pesquisarprod_quant)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_pesquisarprod_quant, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_pesquisarprod_buscar)
                    .addComponent(txt_pesquisarprod_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_pesquisarprod_buscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(lbl_pesquisarprod_quant)
                    .addComponent(txt_pesquisarprod_quant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_pesquisarprod_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pesquisarprod_buscarActionPerformed
        // TODO add your handling code here:
        buscar();
    }//GEN-LAST:event_btn_pesquisarprod_buscarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        adicionar_produto();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txt_pesquisarprod_buscarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_pesquisarprod_buscarKeyPressed

        if (evt.getKeyCode() == evt.VK_ENTER) {
            // Chama a função f() quando a tecla Enter é pressionada
            buscar();
        }
    }//GEN-LAST:event_txt_pesquisarprod_buscarKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPesquisarProd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPesquisarProd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPesquisarProd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPesquisarProd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPesquisarProd().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_pesquisarprod_buscar;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_pesquisarprod_buscar;
    private javax.swing.JLabel lbl_pesquisarprod_quant;
    private javax.swing.JTable tbl_pesquisarprod_produtos;
    private javax.swing.JTextField txt_pesquisarprod_buscar;
    private javax.swing.JTextField txt_pesquisarprod_quant;
    // End of variables declaration//GEN-END:variables
}
